index.js

I've been getting this error when using these elements in Safari:
> NotSupportedError: A newly constructed custom element must not have attributes
The error only occurs for the bold, italic, link, and task-list elements. It turns out that these elements have a `this.setAttribute` call in their constructors which was causing this error.
According to the "[Requirements for custom element constructors](
https://www.w3.org/TR/custom-elements/#custom-element-conformance)" section of the spec:
> The element must not gain any attributes or children, as this violates the expectations of consumers who use the createElement or createElementNS methods.
> In general, work should be deferred to connectedCallback as much as possible—especially work involving fetching resources or rendering. However, …

Remove setAttribute calls from constructors to comply with Custom Elements spec

---

.babelrc
.eslintrc.json
README.md
index.js
package-lock.json
package.json

- adopt babel-preset-github (drop IE 11)
- stop transforming custom element classes
- check files with Flow

Update for modern browsers

---

index.js
test/test.js

Fixes #1.
With section at the beginning of text–
```
- Fix 
expandSelectedText breaking sentences for block changes
```
```
> Fix 
expandSelectedText breaking sentences for block changes
```
```
- Fix expandSelectedText breaking sentences for block changes
```
```
> Fix expandSelectedText breaking sentences for block changes
```
Ordered list has a special case behavior, which remains unchanged.
```
1.
Fix expandSelectedText breaking sentences for block changes
```
Inline markdown changes (bold/italic/link) remain on changed (ie will only expand to the first word). For example:
```
**Fix** expandSelectedText breaking sentences for block changes
```

Fix expandSelectedText breaking sentences for block changes

---

index.js
test/test.js

Reference: https://github.com/github/github/issues/110601#issuecomment-485593356.
1. Set cursor to end of line after inserting OL so user can start typing. Given– 
```
text
|text
```
Clicking on <kbd>OL</kbd>:
| Before | After |
|--|--|
|![image](https://user-images.githubusercontent.com/1153134/56608853-b6299d80-65d9-11e9-8151-81b3894b416d.png)|![image](https://user-images.githubusercontent.com/1153134/56609017-20424280-65da-11e9-8ce3-6026c36ad270.png)|
I believe previously a selection is set so people can click the button again to undo the insertion, which brings us to the second change 👇 .
2. Support undoing OL without selection. Given–
```
text
1. t|ext
```
Clicking on <kbd>OL</kbd>:
| Before | After |
|--|--|
|![image](https://user-images.githubusercontent.com/1153134/56608917-de19010 …

OrderedList fixes

---

index.d.ts
package-lock.json
package.json

Ref: https://github.com/github/web-systems/issues/223

add typescript definition file

---

examples/index.html

I keep messing this up and accidentally pushing those changes to PRs. What do you think about taking the manual editing of comments out of the equation and just load the correct script for the correct environment?
When running locally, you'll get the locally build bundle and when on gh-pages we'll load the unpkg one.
Ref: https://github.com/github/custom-element-boilerplate/pull/13

Load bundles based on what environment the user is in

---

index.js
test/test.js

Hi,
I'll tidy this up and add tests/docs but wanted to get thoughts on adding attribute support for setting the heading level instead of it always being h3 (###). Example usage:
`<md-header level="1">h1</md-header>`
`<md-header level="6">h6</md-header>`
Paul

add attribute support for setting the heading level

---

index.js
test/test.js

If a user tries to set heading to a level above 6, we just don't do anything.
cc/ @muan @mintbridge 
Fixes https://github.com/github/markdown-toolbar-element/issues/23

No more then six levels of headers

---

README.md
examples/index.html
index.js
test/test.js

This follows best practices for toolbar focus management, following the guidelines available at https://www.w3.org/TR/wai-aria-practices-1.1/examples/toolbar/toolbar.html.
ArrowLeft/ArrowRight will switch tabindex/focus the next and previous buttons respectively, cycling round the whole toolbar if needed. Home and End keys were also implemented.
Refs https://github.com/github/github/issues/133916

Feat add focus management for toolbar

---

index.js

If markdown-toolbar-element and textarea are located in a shadow context, the element can't find the textarea.

Fix search a for element in shadow context

---

src/index.ts

Using string concatentation with user controlled input to build a selector query results in syntax errors.
> SyntaxError: Failed to execute 'querySelector' on 'Element': '[hotkey="""]' is not a valid selector.
Instead, query potential hotkey buttons and test their attribute against the event's key value.

Fix invalid selector in hotkey query

---

examples/index.html
src/index.ts
test/test.js

I realize this library is primarily meant for internal use at GitHub, but it's come in handy on a project I'm working on. I would really ~~like~~ love to see support for strikethrough formatting, though! 😉 
This PR:
- Updates `src/index.ts` to add support for `md-strikethrough`.
- Updates `examples/index.html` to add strikethrough to the example toolbars.
- Updates `test/test.js` accordingly.

Add support for strikethrough

---

src/index.ts
test/test.js

This PR does the following:
* adds a hotkey of `C` for the `MarkdownCodeButtonElement`
* forces hotkeys to be case sensitive
References: https://github.com/github/special-projects/issues/135
Demonstrating the current behavior of hotkeys not being case sensitive:
**Low risk**

Add hotkey to code block button

---

src/index.ts
test/test.js

After some further discussion, design would like to change the hotkey to be lowercase to match the other shortcuts in use.
So, this PR:
* changes code hotkey from `cmd-shift-e` to `cmd-e` (in other words, uppercase `E` to lowercase `e`)
References: https://github.com/github/special-projects/issues/135
Keycastr was acting up on me here, but I was pressing `⌘+e`:
**Low risk**

Change code block hotkey from E -> e

---

src/index.ts
test/test.js

This is the first part of https://github.com/github/special-projects/issues/524
The second part will be a `github/github` PR, which will update the vendored version of this module, and also add in tooltips.
This PR introduces a new `hotkey-requires-shift` attribute to allow hotkeys like `cmd+shift+8` (`*` is not be above `8` on all keyboards so that can't be used to mean the same as `shift+8`).
I'd appreciate any pointers about testing this. I did so locally by modifying the vendored `node_modules/@github/markdown-toolbar-element/dist/index.js` manually. Is that sufficient? Once I have a PR for updating the release number in `packages.json` in `github/github`, that could be tested on review lab.
I had a go at updating `packages.json` in `github/github` to point at this branch and running …

New keyboard shortcuts for quotes, bullets and numbered lists

---

src/index.ts
test/test.js

This is to avoid conflicting with github's existing saved-reply shortcut

Require pressing shift for the quote hotkey

---

src/index.ts
test/test.js

Operating hotkeys in a markdown toolbar is out of scope for this web component. Consumers of this component that would like hotkey functionality should rather use a hotkey library such as [`github/hotkey`](https://github.com/github/hotkey).
Adding `data-hotkey="Meta+b"` for the `<md-bold>` button should be the functional equivalent of the existing functionality and the same logic can be applied to the other buttons that have hotkeys enabled.

Remove hotkey functionality

---

src/index.ts
test/test.js

This PR attempts to make list behaviors more consistent and also fixes list stacking.
| Before | After |
|--------|--------|
| ![stacking-before](https://user-images.githubusercontent.com/121539/144333125-504fa97f-c45a-43f3-90c7-a44b617ceb83.gif) | ![stacking-after](https://user-images.githubusercontent.com/121539/144333134-47296684-19b2-4f32-9a4b-4365814417f6.gif) |
This PR aims to make the behavior of ordered and unordered lists more consistent.
We now always consider the whole line instead of relying on selection or caret position.
If no text is selected, the current caret position is retained (that is also true for when undoing a list).
If text is selected, the whole line that was considered for the operation will be selected after the operation is complete.
This resolves an …

Make list behaviors more consistent, fix list stacking

---

src/index.ts
test/test.js

Building a header button in memory with a custom heading ("level") causes a unexpected behaviour. Consider the following example:
```js
const headerButton = document.createElement('md-header') // The constructor is executed at this point.
headerButton.setAttribute('level', '1')                  // Has no effect since the style has already been set.
headerButton.textContent = 'h1'
document.body.appendChild(headerButton)
```
While we expect to have a header button that outputs a single hash (`#`), we have a button that outputs three (`###`). The constructor sets the styles based on the `level` attribute when the component is initialised. Changing the constructor to a `connectedCallback` function ensures that the button styles aren't set until the button is connected to the DOM.
Since …

Use the connectedCallback function to set button styles instead of the constructor

---

src/index.ts
test/test.js

This allows opting out of focus management to use another tool to manage focus instead.
/cc @jonrohan

allow opt out of focus management

---

src/index.ts
test/test.js

This allows the use of `data-md-button={style}`, where `style` is a specific style like `code`, `header-6`, etc.
The _intent_ of this is to allow arbitrary tags like `<div>` or `<button>` to be used over the `<md-button>` variants.
/cc @jonrohan

allow use of <button> elements with `data-md-button="{style}"

---

src/index.ts
test/test.js

The `markdown-toolbar` element is grabbing focus when using `data-no-focus`. I think this is because of the tabindex that's being applied.
To fix this, I'm moving the `this.hasAttribute('data-no-focus')` into the connectedCallback constructor and also avoiding adding eventListeners when this occurs

Don't set a tabindex=0 when the toolbar has data-no-focus attribute applied
